# Análise de Dados de Jogadores de Futebol 
## OBJETIVO
Explorar uma base de dados de jogadores para responder perguntas utilizando Python e Pandas.

**ferramentas utilizadas:**
- Python
- Pandas 
- Jupyter Notebook

In [1]:
import pandas as pd

In [2]:
tabela = pd.read_csv("players.csv")

In [3]:
tabela

,player_id,player_name,team_id,position,age,matches_played_2025_26,goals_2025_26,assists_2025_26,xG,xA,minutes_played,injury_risk,market_value_million,nationality,club,fatigue_score,social_mention_count
0,P0001,Lionel Messi,T017,DF,36,16,18,3,0.65,0.33,459,Low,100,France,Bayern Munich,79.4,174823
1,P0002,Erling Haaland,T009,DF,25,12,14,12,0.58,0.46,3385,Low,52,Argentina,Real Madrid,87.1,218135
2,P0003,Neymar Jr,T033,GK,34,38,3,11,0.90,0.22,3549,Medium,74,Brazil,Manchester City,59.6,111511
3,P0004,Erling Haaland,T020,FW,22,33,20,12,0.94,0.57,2759,Low,104,Germany,Bayern Munich,81.7,225461
4,P0005,Thomas Muller,T013,DF,33,12,12,13,0.27,0.29,1311,Low,63,France,Manchester City,56.2,150830
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19195,P0296,Thomas Muller,T013,DF,25,32,20,3,0.62,0.48,2362,Low,173,Argentina,Bayern Munich,82.2,22241
19196,P0297,Neymar Jr,T043,FW,32,25,1,5,0.15,0.43,3083,Low,112,Germany,PSG,63.9,57975
19197,P0298,Harry Kane,T003,DF,31,24,3,3,0.25,0.55,1445,High,122,Brazil,Inter Miami,64.6,159226
19198,P0299,Erling Haaland,T033,DF,35,34,24,6,0.40,0.58,2624,Low,161,Spain,Bayern Munich,74.0,161697
19199,P0300,Kylian Mbappe,T006,MF,37,20,14,6,1.17,0.11,1881,Medium,87,Argentina,Real Madrid,76.6,181022

In [4]:
tabela.shape

(19200, 17)

In [5]:
tabela.duplicated().sum()

np.int64(18900)

In [6]:
tabela.drop_duplicates()

,player_id,player_name,team_id,position,age,matches_played_2025_26,goals_2025_26,assists_2025_26,xG,xA,minutes_played,injury_risk,market_value_million,nationality,club,fatigue_score,social_mention_count
0,P0001,Lionel Messi,T017,DF,36,16,18,3,0.65,0.33,459,Low,100,France,Bayern Munich,79.4,174823
1,P0002,Erling Haaland,T009,DF,25,12,14,12,0.58,0.46,3385,Low,52,Argentina,Real Madrid,87.1,218135
2,P0003,Neymar Jr,T033,GK,34,38,3,11,0.90,0.22,3549,Medium,74,Brazil,Manchester City,59.6,111511
3,P0004,Erling Haaland,T020,FW,22,33,20,12,0.94,0.57,2759,Low,104,Germany,Bayern Munich,81.7,225461
4,P0005,Thomas Muller,T013,DF,33,12,12,13,0.27,0.29,1311,Low,63,France,Manchester City,56.2,150830
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,P0296,Thomas Muller,T013,DF,25,32,20,3,0.62,0.48,2362,Low,173,Argentina,Bayern Munich,82.2,22241
296,P0297,Neymar Jr,T043,FW,32,25,1,5,0.15,0.43,3083,Low,112,Germany,PSG,63.9,57975
297,P0298,Harry Kane,T003,DF,31,24,3,3,0.25,0.55,1445,High,122,Brazil,Inter Miami,64.6,159226
298,P0299,Erling Haaland,T033,DF,35,34,24,6,0.40,0.58,2624,Low,161,Spain,Bayern Munich,74.0,161697
299,P0300,Kylian Mbappe,T006,MF,37,20,14,6,1.17,0.11,1881,Medium,87,Argentina,Real Madrid,76.6,181022

# Análise inicial da base
Foi realizada uma inspeção inicial do dataset para identificar possíveis problemas de qualidade dos dados, como valores ausentes e registros duplicados. 

**códigos usados**
- tabela.shape
- tabela.duplicated().sum()
- tabela = tabela.drop_duplicates()

In [7]:
tabela.shape
tabela.duplicated().sum()
tabela = tabela.drop_duplicates()

In [8]:
tabela

,player_id,player_name,team_id,position,age,matches_played_2025_26,goals_2025_26,assists_2025_26,xG,xA,minutes_played,injury_risk,market_value_million,nationality,club,fatigue_score,social_mention_count
0,P0001,Lionel Messi,T017,DF,36,16,18,3,0.65,0.33,459,Low,100,France,Bayern Munich,79.4,174823
1,P0002,Erling Haaland,T009,DF,25,12,14,12,0.58,0.46,3385,Low,52,Argentina,Real Madrid,87.1,218135
2,P0003,Neymar Jr,T033,GK,34,38,3,11,0.90,0.22,3549,Medium,74,Brazil,Manchester City,59.6,111511
3,P0004,Erling Haaland,T020,FW,22,33,20,12,0.94,0.57,2759,Low,104,Germany,Bayern Munich,81.7,225461
4,P0005,Thomas Muller,T013,DF,33,12,12,13,0.27,0.29,1311,Low,63,France,Manchester City,56.2,150830
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,P0296,Thomas Muller,T013,DF,25,32,20,3,0.62,0.48,2362,Low,173,Argentina,Bayern Munich,82.2,22241
296,P0297,Neymar Jr,T043,FW,32,25,1,5,0.15,0.43,3083,Low,112,Germany,PSG,63.9,57975
297,P0298,Harry Kane,T003,DF,31,24,3,3,0.25,0.55,1445,High,122,Brazil,Inter Miami,64.6,159226
298,P0299,Erling Haaland,T033,DF,35,34,24,6,0.40,0.58,2624,Low,161,Spain,Bayern Munich,74.0,161697
299,P0300,Kylian Mbappe,T006,MF,37,20,14,6,1.17,0.11,1881,Medium,87,Argentina,Real Madrid,76.6,181022

# SIMPLIFICAR E RENOMEAR 
    Nesta etapa vamos simplificar a tabela para que se mantenha apenas as informações que vamos utilizar para explorar a base e renomeá-las para a praticidade da codificação do projeto.

In [9]:
tabela = tabela [
    ["player_name", "age", "position", "goals_2025_26", "assists_2025_26", "market_value_million", "club", "nationality"
     ]
]

In [10]:
tabela = tabela.rename(columns={
    "player_name": "jogador",
    "age": "idade",
    "position": "posicao",
    "goals_2025_26": "gols",
    "assists_2025_26": "assistencias",
    "market_value_million": "valor_mercado",
    "Club": "clube",
    "nationality": "nacionalidade"
})

tabela

,jogador,idade,posicao,gols,assistencias,valor_mercado,club,nacionalidade
0,Lionel Messi,36,DF,18,3,100,Bayern Munich,France
1,Erling Haaland,25,DF,14,12,52,Real Madrid,Argentina
2,Neymar Jr,34,GK,3,11,74,Manchester City,Brazil
3,Erling Haaland,22,FW,20,12,104,Bayern Munich,Germany
4,Thomas Muller,33,DF,12,13,63,Manchester City,France
...,...,...,...,...,...,...,...,...
295,Thomas Muller,25,DF,20,3,173,Bayern Munich,Argentina
296,Neymar Jr,32,FW,1,5,112,PSG,Germany
297,Harry Kane,31,DF,3,3,122,Inter Miami,Brazil
298,Erling Haaland,35,DF,24,6,161,Bayern Munich,Spain
299,Kylian Mbappe,37,MF,14,6,87,Real Madrid,Argentina

# JOGADOR QUE MAIS MARCOU GOLS NESTA TEMPORADA?

In [11]:
tabela.loc[tabela["gols"].idxmax()]

jogador          Thomas Muller
idade                       35
posicao                     MF
gols                        24
assistencias                 3
valor_mercado               49
club             Bayern Munich
nacionalidade          Germany
Name: 25, dtype: object

# RANKING DOS 10 JOGADORES

In [12]:
top_goleadores = tabela.sort_values(
    by="gols",
    ascending=False
)

top_goleadores.head(10)

,jogador,idade,posicao,gols,assistencias,valor_mercado,club,nacionalidade
298,Erling Haaland,35,DF,24,6,161,Bayern Munich,Spain
273,Kylian Mbappe,32,DF,24,6,57,Bayern Munich,Argentina
225,Kylian Mbappe,22,MF,24,9,142,Inter Miami,France
25,Thomas Muller,35,MF,24,3,49,Bayern Munich,Germany
174,Lionel Messi,25,MF,24,14,59,Inter Miami,France
200,Thomas Muller,35,DF,24,9,131,Bayern Munich,France
178,Thomas Muller,23,DF,24,12,114,Inter Miami,Germany
104,Vinicius Jr,21,FW,24,4,138,Real Madrid,Spain
105,Harry Kane,25,FW,24,7,111,Bayern Munich,England
290,Lionel Messi,29,DF,24,4,60,Manchester City,England

# TOP 10 JOGADORES POR VALOR DE MERCADO:

Nesta análise, os jogadores foram classificados de acordo com o valor de mercado, identificando os dez atletas mais valorizados da base de dados. Essa análise permite observar quais jogadores possuem maior valorização financeira na temporada analisada.

In [13]:
top_valor_mercado = tabela.sort_values(
    by="valor_mercado",
    ascending=False 
)
top_valor_mercado

,jogador,idade,posicao,gols,assistencias,valor_mercado,club,nacionalidade
248,Vinicius Jr,23,MF,5,12,179,Real Madrid,France
243,Thomas Muller,37,GK,9,3,179,Real Madrid,Argentina
96,Thomas Muller,23,MF,14,7,178,Inter Miami,France
276,Erling Haaland,37,MF,21,4,175,Bayern Munich,Spain
223,Jude Bellingham,19,GK,20,14,174,Inter Miami,Argentina
...,...,...,...,...,...,...,...,...
194,Harry Kane,30,DF,4,4,9,Bayern Munich,France
132,Kylian Mbappe,23,MF,3,8,8,Manchester City,Argentina
141,Erling Haaland,26,FW,12,1,7,Bayern Munich,Spain
5,Thomas Muller,23,FW,21,17,6,Bayern Munich,France
116,Neymar Jr,23,GK,16,5,6,Bayern Munich,Argentina

Neste projeto, foi realizado uma análise exploratória de um conjunto de dados de jogadores de futebol da temporada 2025/26. Após o tratamento dos dados, incluindo a remoção de registros duplicados, foram identificados os principais goleadores e os jogadores com maior valor de mercado. O projeto demonstra conhecimentos em manipulação de dados com Pandas, limpeza de dados e análise exploratória utilizando Python.